import { emptyItem, emptyTimeWindow, type WorkData, type Outcome, type Capability, type CapabilitySignal, type PlanningOption, type WorkItem, type CoordinationOpportunity } from '../app/shared/model';
import { portfolioSourceText } from '../app/shared/portfolio';

type PortfolioExample = Pick<WorkData, 'outcomes' | 'capabilities' | 'signals' | 'opportunities' | 'decisions' | 'commitments' | 'items'>;

export function portfolioExample(existing: WorkData, adminId: string, now = new Date()): PortfolioExample {
  for (const id of ['sample-network', 'sample-platform', 'sample-release']) {
    if (!existing.workstreams.some(stream => stream.id === id)) throw new Error(`The synthetic example needs workstream ${id}; no real workstream is substituted.`);
  }
  const at = now.toISOString();
  const day = (offset: number) => new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + offset)).toISOString().slice(0, 10);
  const window = (start: number, end: number, certainty: 'forecast' | 'committed') => ({ start: day(start), end: day(end), certainty, note: 'Synthetic planning example, not an actual delivery commitment.' });
  const task = (id: string, title: string, workstreamId: string, start: number | null, end: number | null, kind: WorkItem['kind'] = 'task'): WorkItem => ({ ...emptyItem(workstreamId), id, title, description: `Synthetic coordination example: ${title}. Use this record to explore choices; replace it with actual work before operational use.`, ownerId: adminId, assigneeIds: [adminId], kind, plannedStart: start === null ? null : day(start), plannedEnd: end === null ? null : day(end), targetDate: end === null ? null : day(end), createdAt: at, updatedAt: at, completedAt: null });
  const items = [
    task('sample-shared-onboarding', 'Build reusable workload onboarding', 'sample-platform', 30, 65),
    task('sample-shared-onboarding-ready', 'Accept shared onboarding interface', 'sample-platform', 70, 70, 'milestone'),
    task('sample-local-onboarding', 'Prepare first-workload onboarding adapter', 'sample-release', 5, 20),
    task('sample-retire-onboarding-adapter', 'Retire the temporary onboarding adapter', 'sample-release', null, null),
  ];
  const outcomes: Outcome[] = [
    { id: 'sample-outcome-connectivity', workstreamId: 'sample-network', title: 'Publish a stable production connectivity contract', description: 'Synthetic outcome. Produce approved production cluster addressing and connectivity for workload teams. The contract is needed before first-workload onboarding.', ownerId: adminId, priority: 'high', status: 'active', window: window(5, 8, 'forecast'), itemIds: ['sample-ip-plan', 'sample-network-ready'], createdAt: at, updatedAt: at },
    { id: 'sample-outcome-shared-onboarding', workstreamId: 'sample-platform', title: 'Offer reusable workload onboarding', description: 'Synthetic outcome. Produce a reusable production onboarding interface between 45 and 75 days from this example. Teams can share the interface contract earlier; full service availability is a forecast, not a commitment.', ownerId: adminId, priority: 'normal', status: 'planned', window: window(45, 75, 'forecast'), itemIds: ['sample-shared-onboarding', 'sample-shared-onboarding-ready'], createdAt: at, updatedAt: at },
    { id: 'sample-outcome-first-workload', workstreamId: 'sample-release', title: 'Deliver the first workload with owned operations', description: 'Synthetic outcome. The first workload requires production onboarding within its near-term release window. Waiting for the reusable service would miss that window. A temporary adapter against an agreed interface is an option, not an approved decision.', ownerId: adminId, priority: 'urgent', status: 'planned', window: window(16, 24, 'committed'), itemIds: ['sample-local-onboarding', 'sample-launch', 'sample-retire-onboarding-adapter'], createdAt: at, updatedAt: at },
  ];
  const capabilities: Capability[] = [
    { id: 'sample-capability-connectivity', name: 'Approved production connectivity', description: 'Stable addressing and connectivity contract for the production cluster.', createdAt: at, updatedAt: at },
    { id: 'sample-capability-onboarding', name: 'Production workload onboarding', description: 'A repeatable onboarding interface with owned operational handover.', createdAt: at, updatedAt: at },
  ];
  const signals: CapabilitySignal[] = [
    { id: 'sample-signal-connectivity-produce', outcomeId: outcomes[0].id, capabilityId: capabilities[0].id, direction: 'produces', scope: 'Production cluster', window: window(5, 8, 'forecast'), note: 'Approved addressing and connectivity contract.', createdAt: at, updatedAt: at },
    { id: 'sample-signal-connectivity-require', outcomeId: outcomes[2].id, capabilityId: capabilities[0].id, direction: 'requires', scope: 'Production cluster', window: window(16, 24, 'committed'), note: 'Needed for the first workload handover.', createdAt: at, updatedAt: at },
    { id: 'sample-signal-onboarding-produce', outcomeId: outcomes[1].id, capabilityId: capabilities[1].id, direction: 'produces', scope: 'Production cluster', window: window(45, 75, 'forecast'), note: 'The shared service is expected after the first workload window.', createdAt: at, updatedAt: at },
    { id: 'sample-signal-onboarding-require', outcomeId: outcomes[2].id, capabilityId: capabilities[1].id, direction: 'requires', scope: 'Production cluster', window: window(16, 24, 'committed'), note: 'A local adapter could meet this requirement without waiting for shared service readiness.', createdAt: at, updatedAt: at },
  ];
  const option = (id: string, title: string, strategy: PlanningOption['strategy'], extra: Partial<PlanningOption>): PlanningOption => ({ id, title, strategy, benefits: '', tradeoffs: '', deliveryImpact: '', resourceImpact: '', coordinationCost: '', reversibility: '', migrationObligation: '', assumptions: [], window: emptyTimeWindow(), dependencies: [], ...extra });
  const staged: WorkData = { ...existing, outcomes, capabilities, signals, items: [...existing.items, ...items] };
  const evidence = outcomes.slice(1).map(outcome => ({ sourceType: 'outcome' as const, sourceId: outcome.id, quote: outcome.description, sourceText: portfolioSourceText(staged, { sourceType: 'outcome', sourceId: outcome.id })! }));
  const opportunities: CoordinationOpportunity[] = [{
    id: 'sample-opportunity-onboarding', title: 'Align shared onboarding without delaying the first workload', kind: 'timing_mismatch', description: 'Synthetic planning comparison. Both workstreams need the same production onboarding capability, but the reusable service is forecast after the near-term delivery window. Shared interface design can be coordinated without immediately coupling delivery.', outcomeIds: [outcomes[1].id, outcomes[2].id], capabilityIds: [capabilities[1].id], window: window(16, 75, 'forecast'), decisionBy: day(5), evidence,
    options: [
      option('sample-option-coordinate', 'Wait for the shared service', 'coordinate_now', { benefits: 'One shared implementation and operating model.', tradeoffs: 'The first workload inherits shared-service delivery risk.', deliveryImpact: 'Requires revisiting the first-workload commitment; dates are not automatically changed.', resourceImpact: 'Local adapter work may be avoided; effort has not been estimated.', coordinationCost: 'Joint acceptance and interface ownership required.', reversibility: 'Switching later to an adapter would require new work.', window: window(45, 75, 'forecast'), dependencies: [{ predecessorId: 'sample-shared-onboarding-ready', successorId: 'sample-local-onboarding', activation: 'now', activateOn: null, milestoneId: null }] }),
      option('sample-option-independent', 'Keep delivery independent', 'independent', { benefits: 'Protect the first-workload delivery window.', tradeoffs: 'Separate implementation and ongoing support may remain.', resourceImpact: 'Requires a named owner for the local solution; effort is unknown.', coordinationCost: 'Agree minimum compatibility expectations only.', reversibility: 'A later migration is possible but is not committed by this choice.', window: window(16, 24, 'committed') }),
      option('sample-option-bridge', 'Use an adapter, then converge', 'temporary_bridge', { benefits: 'Preserve near-term delivery while leaving a shared-service path.', tradeoffs: 'Adapter maintenance and eventual migration work.', deliveryImpact: 'Local delivery does not wait for shared readiness.', coordinationCost: 'Agree the interface now; review service readiness before migration.', reversibility: 'Retain the adapter if acceptance fails; review the decision rather than silently extending it.', migrationObligation: 'Retire the adapter only after shared-interface acceptance and a reviewed migration plan.', assumptions: ['The shared interface can be agreed before the service is ready.'], window: window(16, 75, 'forecast'), dependencies: [{ predecessorId: 'sample-shared-onboarding-ready', successorId: 'sample-retire-onboarding-adapter', activation: 'after_milestone', activateOn: null, milestoneId: 'sample-shared-onboarding-ready' }] }),
      option('sample-option-revisit', 'Gather evidence before choosing', 'revisit', { benefits: 'Avoid premature coupling.', tradeoffs: 'The decision window continues to narrow.', deliveryImpact: 'No delivery commitment changes yet.', assumptions: ['Interface scope and readiness evidence remain incomplete.'] }),
    ], questions: ['Can the shared interface be agreed before service implementation?', 'Who owns and funds adapter retirement?'], origin: 'manual', status: 'open', dismissalReason: '', createdAt: at, updatedAt: at,
  }];
  return { outcomes, capabilities, signals, opportunities, decisions: [], commitments: [], items };
}
